### ISSUE TITLE
Dataset download

### ISSUE THREAD

**Issue by BoLeiChen** [sx-zhang/GMAN#1]
Thank you so much for open sourcing this great work. But I encountered a problem when downloading the dataset, the corresponding link of the dataset in Readme.md is invalid. How can I get the data? Thank you !

**Comment by sx-zhang** [comment]
The dataset will be published soon, thanks for your patience. (I'm in lockdown at home currently due to the COVID‑19 :( )

**Comment by liger88** [comment]
Data can not be downloaded yet all due to COVID-19.

**Comment by sx-zhang** [comment]
The data is released now! Thanks for the patience. (More trained models will also be released soon.)

**Comment by keeper1314** [comment]
> Thank you so much for open sourcing this great work. But I encountered a problem when downloading the dataset, the corresponding link of the dataset in Readme.md is invalid. How can I get the data? Thank you !





> Thank you so much for open sourcing this great work. But I encountered a problem when downloading the dataset, the corresponding link of the dataset in Readme.md is invalid. How can I get the data? Thank you !

Could you please provide information on how to download the dataset? Thank you very much!
